name: cats_vs_zombies
description: Cats vs Zombies - Lulu and Gute Runner Game!
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^17.1.2
  audioplayers: ^6.0.0
  http: ^1.2.0
  timezone: ^0.9.2
  permission_handler: ^11.3.0
  # Flame
  flame: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # Runner game assets
    # cats
    - assets/images/cat/lulu/runner/1.png
    - assets/images/cat/lulu/runner/2.png
    - assets/images/cat/lulu/runner/3.png
    - assets/images/cat/lulu/runner/4.png
    - assets/images/cat/lulu/runner/5.png
    - assets/images/cat/lulu/runner/6.png
    - assets/images/cat/lulu/runner/7.png
    - assets/images/cat/lulu/runner/8.png
    - assets/images/cat/gute/runner/1.png
    - assets/images/cat/gute/runner/2.png
    - assets/images/cat/gute/runner/3.png
    - assets/images/cat/gute/runner/4.png
    - assets/images/cat/gute/runner/5.png
    - assets/images/cat/gute/runner/6.png
    - assets/images/cat/gute/runner/7.png
    - assets/images/cat/gute/runner/8.png
    # cats principal
    - assets/images/cat/lulu/lulu-3d.png
    - assets/images/cat/gute/gute-3d.png
    # scenes
    - assets/images/scenes/1.png
    - assets/images/scenes/2.png
    - assets/images/scenes/3.png
    - assets/images/scenes/4.png
    - assets/images/scenes/5.png
    - assets/images/scenes/6.png
    # boom
    - assets/images/boom/storm.png
    # target
    - assets/images/target/target-1.png
    - assets/images/target/target-2.png
    - assets/images/target/target-3.png
    - assets/images/target/target-4.png
    - assets/images/target/target-5.png
    - assets/images/target/target-6.png
    - assets/images/target/target-7.png
    - assets/images/target/target-8.png
    - assets/images/target/target-9.png
    - assets/images/target/target-10.png
    # final
    - assets/images/end/over.png
    - assets/images/end/win.png
    # principal
    - assets/images/credit.png
    - assets/images/home.png
    - assets/images/avatar.png
    # zombies
    - assets/images/zombies/lulu/1.png
    - assets/images/zombies/lulu/2.png
    - assets/images/zombies/lulu/3.png
    - assets/images/zombies/lulu/4.png
    - assets/images/zombies/lulu/5.png
    - assets/images/zombies/lulu/6.png
    - assets/images/zombies/lulu/7.png
    - assets/images/zombies/lulu/8.png
    - assets/images/zombies/gute/1.png
    - assets/images/zombies/gute/2.png
    - assets/images/zombies/gute/3.png
    - assets/images/zombies/gute/4.png
    - assets/images/zombies/gute/5.png
    - assets/images/zombies/gute/6.png
    - assets/images/zombies/gute/7.png
    - assets/images/zombies/gute/8.png
    # audio
    - assets/audio/miau-music.mp4
    - assets/audio/over.mp4